#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

/* load all available solvers */
$solutions = collect(scandir('src'))
             ->filter(fn($i) => $i[0] !== '.')
             ->map(fn($solver) => '\\Advent\\' . basename($solver, '.php'))
             ->filter(fn($solver) => !isset($argv[1]) || str_contains($solver, str_pad($argv[1], 2, '0', STR_PAD_LEFT)))
             ->map(fn($solver) => new $solver())
             ->reduce(fn($solutions, $solver) => $solutions->merge($solver->solve()), collect());

if ($solutions->count() > 0) {
    render_output($solutions);
}
