#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

$options = getopt("e");

/* load all available solvers */
$solutions = collect(scandir('src'))
             ->filter(fn($i) => $i[0] !== '.')
             ->map(fn($solver) => '\\Advent\\' . basename($solver, '.php'))
             ->filter(fn($solver) => !is_numeric(end($argv)) || str_contains($solver, str_pad(end($argv), 2, '0', STR_PAD_LEFT)))
             ->map(fn($solver) => new $solver($options))
             ->reduce(fn($solutions, $solver) => $solutions->merge($solver->solve()), collect());

if ($solutions->count() > 0) {
    render_output($solutions);
}
